### ISSUE TITLE
Add convert to Title Case  

### ISSUE THREAD

**Issue by seatrout** [timhor/obsidian-editor-shortcuts#2]
Would it be possible to extend the case conversion routine to change the word to title case, as well as toggling between upper and lower case? It looks as if it should be simple enough.

**Comment by timhor** [comment]
Yep, that's a simple addition. So that we're on the same page though – by _title case_, do you mean:
1. Naively capitalising the first character of each word (the programming definition), or
2. Capitalising the first character of each major word, ignoring words like `the`, `a`, `an` (the publishing definition)?

**Comment by seatrout** [comment]
Either would be great, but I would prefer (2). 

My real use case is with single words anyway, because I have and UNcanny ability to hold the shift KEy down one letter too far!

**Comment by timhor** [comment]
Title case has been implemented in 7d47723. You can now also transform case when your cursor is on a word without needing to select it first (07596d2).

**Comment by seatrout** [comment]
Thank you. But it doesn't show up as a command to which a hotkey can be attached. The other two case manipulations do.

**Comment by timhor** [comment]
Are you on the latest version v1.1.0?

**Comment by seatrout** [comment]
Ah. No: I wasn't. I installed yesterday morning (GMT) and you obviously upgraded in the last 24 hours. Thanks!
