### ISSUE TITLE
CMD + D Doesn't seem to work in some cases

### ISSUE THREAD

**Issue by mgmeyers** [timhor/obsidian-editor-shortcuts#35]
For example:

```
(hello)
(hello)
(hello)
```

Selecting the first `(hello)` and hitting `cmd + D` doesn't select the next one. But just selecting `hello` works.

Do you think it's maybe that searchText needs to be escaped here?

https://github.com/timhor/obsidian-editor-shortcuts/blob/1e0e6e6816e2cac50ec07b33decaf829d6ee4e93/src/utils.ts#L266

Eg. https://www.npmjs.com/package/escape-string-regexp

**Comment by timhor** [comment]
Yes, good catch! Fix incoming in the next release 😄

**Comment by timhor** [comment]
@brandonlilly That was somewhat intentional. When expanding to the next match, Sublime distinguishes between how the initial selection was made:

- If it was done via `Cmd`+`D` (expanding from a cursor selection), it will not match within words
- If it was done 'by hand' (using a mouse or `Shift` + arrow keys), it will match within words

I made an initial call to emulate the former, but have since [updated it to search within words](https://github.com/timhor/obsidian-editor-shortcuts/commit/282fffcc0bad017590300d7b825d8371524fc5d1). I'm hoping to have the logic for both scenarios completed next week.

In the meantime, you can grab the latest copy of `master` if that's the preferred behaviour for you.

**Comment by timhor** [comment]
Both fixes have been released in [v1.9.0](https://github.com/timhor/obsidian-editor-shortcuts/releases/tag/1.9.0)
